### ISSUE TITLE
How do use touch in v9?

### ISSUE THREAD

**Issue by pan1024** [lvgl/lv_port_linux#43]

**Comment by pan1024** [comment]
step 1:set #define LV_USE_EVDEV    1 in lv_config.h
step2:add lv_evdev_create(LV_INDEV_TYPE_POINTER,"/dev/input/event0"); in main function and set the second parameter

**Comment by kisvegabor** [comment]
So have you found the answer and was it working well. 

If so you could you open a Pull request to update the README with information that would have been useful for you to get started with v9?

**Comment by pan1024** [comment]
> So have you found the answer and was it working well?
> 
> If so you could you open a Pull request to update the README with information that would have been useful for you to get started with v9?

It works very well，and I think we should modify main.c, not the README, to provide a quick way for users to use it

**Comment by kisvegabor** [comment]
Sounds good!
